services:
  - type: web
    name: quotation-app-admin
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://quotation-app-backend.onrender.com/api
